#!/usr/bin/env python3
"""Builds the case study pages in /projects/<slug>/index.html from the content below.

Every visible string is a (spanish, english) pair. Spanish goes in the markup (it is the default
and what shows without JavaScript); English is emitted to window.I18N_EN for assets/js/site.js.
Run: python3 tools/build_projects.py
"""
import html
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ARROW_UR = '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M6 18L18 6M18 15V6H9"/></svg>'
ARROW_L = '<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M20 12H4m0 0l6 6m-6-6l6-6"/></svg>'


class Page:
    def __init__(self, slug):
        self.slug = slug
        self.en = {}
        self.n = 0

    def tr(self, pair, tag='span', attrs='', html_ok=False):
        """Render a translatable element and register its English copy."""
        es, en = pair
        self.n += 1
        key = f'{self.slug}.{self.n}'
        self.en[key] = en
        extra = ' data-html' if html_ok else ''
        body = es if html_ok else html.escape(es)
        return f'<{tag} data-i18n="{key}"{extra}{attrs}>{body}</{tag}>'


def meta_item(p, label, value, link=None):
    if link:
        v = f'<a href="{link}" target="_blank" rel="noopener">{html.escape(value)}</a>'
        return f'<div><dt class="mono">{p.tr(label)}</dt><dd>{v}</dd></div>'
    val = p.tr(value) if isinstance(value, tuple) else html.escape(value)
    return f'<div><dt class="mono">{p.tr(label)}</dt><dd>{val}</dd></div>'


def block(p, label, title, content):
    return f'''
      <section>
        <div class="wrap cs-block">
          <header>
            {p.tr(label, attrs=' class="chapter-label mono"')}
            {p.tr(title, tag='h2', attrs=' data-split')}
          </header>
          <div class="cs-content" data-reveal>
            {content}
          </div>
        </div>
      </section>'''


def paras(p, items):
    return '\n            '.join(p.tr(x, tag='p') for x in items)


def items(p, rows):
    lis = ''.join(f'<li>{p.tr(t, tag="h3")}{p.tr(d, tag="p")}</li>' for t, d in rows)
    return f'<ul class="cs-list">{lis}</ul>'


def stats(p, rows):
    cells = ''.join(f'<div class="stat"><b>{html.escape(n)}</b>{p.tr(d)}</div>' for n, d in rows)
    return f'<div class="stats">{cells}</div>'


def pipeline(p, steps):
    cells = ''.join(f'<div><span class="mono">{p.tr(t)}</span>{p.tr(d, tag="p")}</div>' for t, d in steps)
    return f'<div class="pipeline">{cells}</div>'


def spec(p, rows):
    cells = ''.join(f'<div><dt class="mono">{p.tr(t)}</dt><dd>{p.tr(d)}</dd></div>' for t, d in rows)
    return f'<dl class="spec">{cells}</dl>'


def page_html(p, d, body):
    # register every header string before serializing the English dictionary
    meta = ''.join(meta_item(p, *m) for m in d['meta'])
    label = p.tr(d['label'], attrs=' class="chapter-label mono" data-intro')
    title = p.tr((d['name'], d.get('name_en', d['name'])), tag='h1', attrs=' class="cs-title" data-split')
    lede = p.tr(d['lede'], tag='p', attrs=' class="cs-lede" data-intro')
    nxt = p.tr(d['next'][1])
    cover = d['cover'](p)
    en_js = ',\n      '.join(f"{json.dumps(k)}: {json.dumps(v, ensure_ascii=False)}" for k, v in p.en.items())
    return f'''<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
  <title>{html.escape(d['name'])} · Case study · Braian Arroyo Braconi</title>
  <meta name="description" content="{html.escape(d['description'])}"/>
  <meta property="og:title" content="{html.escape(d['name'])} · Braian Arroyo Braconi"/>
  <meta property="og:description" content="{html.escape(d['description'])}"/>
  <meta property="og:type" content="article"/>
  <meta property="og:url" content="https://www.braianarroyo.com/projects/{p.slug}/"/>
  <meta name="theme-color" content="#0b0b0c"/>
  <meta name="color-scheme" content="dark"/>
  <link rel="canonical" href="https://www.braianarroyo.com/projects/{p.slug}/"/>
  <link rel="preload" href="/assets/fonts/Geist.woff2" as="font" type="font/woff2" crossorigin/>
  <link rel="stylesheet" href="/assets/css/site.css"/>
  <!-- Generated by tools/build_projects.py. Edit the content there, not here. -->
</head>
<body>

  <div class="bar">
    <div class="wrap bar-inner">
      <a href="/" class="brand">Braian Arroyo Braconi</a>
      <div class="bar-right">
        <a class="back" href="/after-hours/">{ARROW_L}<span data-i18n="back">Volver</span></a>
        <div class="lang" role="group" aria-label="Idioma / Language" data-active="es">
          <button type="button" data-lang="es" aria-pressed="true">ES</button>
          <button type="button" data-lang="en" aria-pressed="false">EN</button>
        </div>
      </div>
    </div>
  </div>

  <main id="top">
    <header class="cs-hero" data-intro-root>
      <div class="wrap">
        {label}
        {title}
        {lede}
        <dl class="cs-meta mono-meta" data-intro>{meta}</dl>
      </div>
      <div class="wrap" style="margin-top:56px">
        {cover}
      </div>
    </header>

    <div class="cs-body">
{body}
    </div>

    <div class="wrap">
      <a class="next-case" href="/projects/{d['next'][0]}/">
        <span class="mono" data-i18n="next">Siguiente proyecto</span>
        <strong>{nxt} {ARROW_UR}</strong>
      </a>
    </div>

    <section class="cta-band" aria-labelledby="cta-title">
      <div class="wrap">
        <h2 id="cta-title" data-i18n="cta.title">Hablemos.</h2>
        <a class="btn btn-solid" href="mailto:braianarroyobraconi@gmail.com"><span data-i18n="cta.button">Escribime</span>{ARROW_UR}</a>
      </div>
    </section>
  </main>

  <footer>
    <div class="wrap">
      <span>© 2026 Braian Arroyo Braconi</span>
      <nav aria-label="Footer">
        <a href="/">Home</a>
        <a href="https://linkedin.com/in/braianarroyobraconi" target="_blank" rel="noopener">LinkedIn</a>
        <a href="#top" data-i18n="footer.top">Volver arriba</a>
      </nav>
    </div>
  </footer>

  <script src="/assets/vendor/gsap.min.js" defer></script>
  <script src="/assets/vendor/ScrollTrigger.min.js" defer></script>
  <script src="/assets/vendor/lenis.min.js" defer></script>
  <script>
    window.I18N_EN = {{
      'next': 'Next project',
      {en_js}
    }};
  </script>
{'  <script src="/assets/js/lamp.js"></script>' + chr(10) if d.get('lamp') else ''}  <script src="/assets/js/site.js"></script>
</body>
</html>
'''


# ---------------------------------------------------------------- content

ROLE = ('Rol', 'Role')
YEAR = ('Año', 'Year')
STATUS = ('Estado', 'Status')
STACK = ('Stack', 'Stack')
LINK = ('Link', 'Link')


def pegote():
    p = Page('pegote')

    def cover(p):
        return f'''<figure class="cs-cover" data-unveil style="aspect-ratio:16/9;background:var(--f-pegote)">
          <img src="/assets/img/projects/pegote-diario-viaje.webp" alt="" style="object-position:50% 30%" data-parallax/>
        </figure>'''

    body = ''.join([
        block(p, ('Contexto', 'Context'), ('Un juguete, no un editor.', 'A toy, not an editor.'), paras(p, [
            ('Quería llevar a la pantalla el placer físico de los stickers y el scrapbooking: abrir un sobre sin saber qué trae, despegar con cuidado, ubicar y pegar. La mayoría de las herramientas de collage digitales están pensadas como editores. Pegote está pensado como un juguete: lo importante es cómo se siente cada gesto.',
             'I wanted to bring the physical pleasure of stickers and scrapbooking to the screen: opening a pack without knowing what is inside, peeling carefully, placing and sticking. Most digital collage tools are built as editors. Pegote is built as a toy: what matters is how each gesture feels.'),
            ('Es un proyecto propio de punta a punta: diseño de producto, diseño de interacción, ilustración, desarrollo, analítica, comunicación y comunidad.',
             'It is a personal project end to end: product design, interaction design, illustration, development, analytics, communication and community.'),
        ])),
        block(p, ('Qué construí', 'What I built'), ('Un mundo de papel que responde al tacto.', 'A paper world that responds to touch.'), items(p, [
            (('Física de despegue', 'Peeling physics'),
             ('El sticker se dobla por el punto exacto donde lo agarrás, con la solapa reflejada en tiempo real. Los que están encimados se despegan juntos y, si tirás rápido de uno ya pegado, se rompe.',
              'The sticker folds at the exact point where you grab it, with the flap mirrored in real time. Overlapping stickers peel off together and, if you pull a placed one too fast, it tears.')),
            (('Mesa de trabajo', 'Workbench'),
             ('Materiales, troqueles y una tijera de corte libre con filos (ondas, zigzag, estampilla, rasgado) para fabricar piezas propias a partir de papeles y recortes.',
              'Materials, die cuts and freehand scissors with edge styles (waves, zigzag, stamp, torn) to make your own pieces out of papers and cutouts.')),
            (('Hojas, cuadernos e historias', 'Sheets, notebooks and stories'),
             ('Varias páginas por persona, cuaderno abierto con anillado y formato de historia de Instagram con plantillas editables, fotos con máscara y texto.',
              'Multiple pages per person, an open spiral notebook and an Instagram story format with editable templates, masked photos and text.')),
            (('Regalos con notita', 'Gifts with a note'),
             ('Compartís una hoja con un mensaje escrito o dibujado y le llega a la otra persona como una carta animada, sin que necesite cuenta.',
              'You share a sheet with a written or hand-drawn message and it arrives to the other person as an animated letter, no account needed.')),
            (('Colección y llegadas', 'Collection and drops'),
             ('Series de sobres con rarezas (holográficos, brillantina, dorados), ediciones especiales por código y contenido que llega en fechas programadas.',
              'Pack series with rarities (holographic, glitter, gold), special editions unlocked by code and content that arrives on scheduled dates.')),
        ])),
        block(p, ('Decisiones de diseño', 'Design decisions'), ('Menos interfaz, más gesto.', 'Less interface, more gesture.'), items(p, [
            (('Sin modos', 'No modes'),
             ('La tijera mueve una pieza si la arrastrás y la corta si la mantenés apretada. Se probó con modos y se descartó: cada cambio de modo era un paso más entre la intención y el gesto.',
              'The scissors move a piece if you drag it and cut it if you hold it. A version with modes was tested and dropped: every mode switch was one more step between intent and gesture.')),
            (('Celular primero', 'Mobile first'),
             ('La navegación es una píldora flotante con Sobres al centro, elegida entre cuatro variantes probadas dentro del juego real. La hoja tiene zoom y paneo mientras la bandeja queda fija, como en las apps de lienzo.',
              'Navigation is a floating pill with Packs in the center, chosen among four variants tested inside the real game. The sheet zooms and pans while the tray stays fixed, as in canvas apps.')),
            (('Sacar también es diseñar', 'Removing is designing too'),
             ('Instrucciones que aparecían al tocar, minijuegos sobre la mesa y una caja extra se sacaron porque interrumpían. El tutorial dejó de arrancar solo y pasó a estar disponible cuando se lo busca.',
              'Hints that appeared on touch, mini-games on the table and an extra box were removed because they interrupted. The tutorial no longer starts on its own and is available when people look for it.')),
            (('Medir antes de sumar', 'Measure before adding'),
             ('Un test A/B del login (ventana aparte o redirección) y un flujo específico para los navegadores dentro de Instagram, que bloquean el login de Google.',
              'An A/B test of the login flow (popup or redirect) and a dedicated flow for in-app browsers like Instagram\'s, which block Google sign-in.')),
        ])),
        block(p, ('Rendimiento', 'Performance'), ('Que se sienta físico también en un celular modesto.', 'Feeling physical on a modest phone too.'), stats(p, [
            ('460 → 19 ms', ('por cuadro en una hoja cargada, en un celular simulado con CPU ×4.', 'per frame on a loaded sheet, on a simulated phone with a 4× slower CPU.')),
            ('2.819 → 43 ms', ('para levantar un sticker ya pegado en una hoja con 250 elementos.', 'to lift an already placed sticker on a sheet with 250 items.')),
        ]) + '\n            ' + paras(p, [
            ('Lo quieto se pinta una sola vez como capa y cada sticker se cachea como imagen propia; solo se redibuja en vivo lo que se mueve. La calidad de dibujo se ajusta sola si los cuadros por segundo caen.',
             'Everything static is painted once as a layer and each sticker is cached as its own image; only what moves is redrawn live. Rendering quality adjusts itself if frame rate drops.'),
        ])),
        block(p, ('Proceso', 'Process'), ('Criterio humano, implementación con IA.', 'Human judgment, AI-assisted build.'), paras(p, [
            ('Lo desarrollo con Claude Code como compañero de programación: yo defino la experiencia, las reglas y la vara de calidad; la IA acelera la implementación y las pruebas. Cada cambio se prueba con capturas automáticas en escritorio y celular.',
             'I build it with Claude Code as a programming partner: I define the experience, the rules and the quality bar; AI speeds up implementation and testing. Every change is checked with automated screenshots on desktop and mobile.'),
            ('Las series de stickers combinan ilustraciones dibujadas en código, dibujos a mano y arte generado con IA procesado con scripts propios. Una serie usa fotos reales con licencia libre de Wikimedia Commons, con página de créditos.',
             'Sticker series combine illustrations drawn in code, hand drawings and AI-generated art processed with my own scripts. One series uses real, freely licensed photos from Wikimedia Commons, with a credits page.'),
            ('El lanzamiento es una alfa con analítica en PostHog: un tablero de 23 gráficos sobre activación, retención, tutorial, paso de invitado a cuenta, canales y uso.',
             'The launch is an alpha with PostHog analytics: a 23-chart dashboard covering activation, retention, onboarding, guest-to-account conversion, channels and usage.'),
        ])),
    ])

    body += f'''
      <div class="wrap">
        <div class="gallery" data-reveal-group>
          <figure class="g-narrow" data-reveal>
            <video src="/assets/img/projects/pegote-regalo.mp4" poster="/assets/img/projects/pegote-regalo-poster.jpg" muted loop playsinline preload="none" data-autoplay style="aspect-ratio:1/1"></video>
            {p.tr(('Grabación real del flujo de regalo: notita, carta y apertura sin cuenta.', 'Real recording of the gift flow: note, letter and opening without an account.'), tag='figcaption')}
          </figure>
          <figure class="g-wide" data-reveal>
            <img src="/assets/img/projects/pegote-pagina-diario.webp" alt="" loading="lazy" style="aspect-ratio:7/6;object-position:50% 35%"/>
            {p.tr(('Una página de diario armada en Pegote.', 'A journal page made in Pegote.'), tag='figcaption')}
          </figure>
          <figure class="g-third g-frame" data-reveal>
            <img src="/assets/img/projects/pegote-despegar.webp" alt="" loading="lazy"/>
            {p.tr(('El despegue, el gesto central.', 'Peeling, the core gesture.'), tag='figcaption')}
          </figure>
          <figure class="g-third g-frame" data-reveal>
            <img src="/assets/img/projects/pegote-series.webp" alt="" loading="lazy"/>
            {p.tr(('Series coleccionables.', 'Collectible series.'), tag='figcaption')}
          </figure>
          <figure class="g-third g-frame" data-reveal>
            <img src="/assets/img/projects/pegote-historias.webp" alt="" loading="lazy" style="object-position:50% 30%"/>
            {p.tr(('Historias de Instagram con plantillas.', 'Instagram stories with templates.'), tag='figcaption')}
          </figure>
        </div>
      </div>'''

    body += block(p, ('Qué sigue', 'What\'s next'), ('Del juego individual a la comunidad.', 'From solo play to community.'), paras(p, [
        ('Un álbum de colección, el intercambio de stickers entre personas como camino a un mercado, y un contador en vivo de usuarios con un ESP32 y una pantalla e-ink, que conecta este proyecto con la Lámpara viva.',
         'A collection album, sticker trading between people as a path to a marketplace, and a live user counter built with an ESP32 and an e-ink display, which connects this project with the Living lamp.'),
    ]))

    d = dict(name='Pegote', description='Case study: Pegote, a web game about stickers and collage, designed and built end to end.',
             label=('Proyecto propio · 2026', 'Side project · 2026'),
             lede=('Un juego web de stickers y collage: abrís sobres, despegás stickers y armás hojas, cuadernos e historias para compartir.',
                   'A web game about stickers and collage: open packs, peel stickers and make sheets, notebooks and stories to share.'),
             meta=[(ROLE, ('Producto, interacción y desarrollo', 'Product, interaction and development')), (YEAR, '2026'),
                   (STATUS, ('Alfa abierta', 'Open alpha')), (LINK, 'pegote.club', 'https://pegote.club')],
             cover=cover, next=('living-lamp', ('Lámpara viva', 'Living lamp')))
    return p, d, body


def lamp():
    p = Page('lamp')

    def cover(p):
        return f'''<div class="lamp-stage" style="border-radius:var(--r)" data-unveil>
          <div class="lamp-poster" aria-hidden="true"></div>
          <canvas role="img" aria-label="Patrón generativo de la lámpara viva" data-i18n-aria="lamp.aria"></canvas>
          <div class="lamp-read mono" aria-hidden="true"><span data-lamp-light>luz 72%</span><span data-lamp-hint>Mové el cursor</span><span data-lamp-temp>temp 8%</span></div>
        </div>'''

    p.en['lamp.aria'] = 'Generative pattern from the living lamp'
    body = ''.join([
        block(p, ('Contexto', 'Context'), ('Diseño de interacción sin pantalla táctil.', 'Interaction design without a touchscreen.'), paras(p, [
            ('Un experimento para llevar el diseño de interacción fuera de la pantalla: un objeto que responde a su entorno sin que nadie lo toque. La luz y la temperatura del ambiente son la interfaz.',
             'An experiment in taking interaction design off the screen: an object that responds to its surroundings without anyone touching it. Ambient light and temperature are the interface.'),
            ('Arriba corre el mismo algoritmo en tu navegador. El cursor reemplaza a los sensores: el eje horizontal es la luz y el vertical, la temperatura.',
             'The same algorithm runs above in your browser. The cursor stands in for the sensors: the horizontal axis is light and the vertical one is temperature.'),
        ])),
        block(p, ('Cómo funciona', 'How it works'), ('Del sensor al patrón.', 'From sensor to pattern.'), pipeline(p, [
            (('Sensores', 'Sensors'), ('Un ESP32 lee una fotorresistencia y un sensor de temperatura analógico.', 'An ESP32 reads a photoresistor and an analog temperature sensor.')),
            (('Calibración', 'Calibration'), ('Guarda el mínimo y el máximo que va viendo y normaliza en ese rango: se adapta a cualquier ambiente.', 'It tracks the minimum and maximum it sees and normalizes within that range, adapting to any room.')),
            (('Curvas', 'Curves'), ('Curvas no lineales para que los cambios chicos se noten: luz al cuadrado, temperatura a la 1,5.', 'Non-linear curves so small changes are felt: light squared, temperature to the 1.5.')),
            (('Envío', 'Transport'), ('Manda luz y temperatura de 0 a 100 por puerto serie cada 80 ms.', 'It sends light and temperature from 0 to 100 over serial every 80 ms.')),
            (('Patrón', 'Pattern'), ('Processing dibuja una grilla de 80 × 80 con diez patrones de ruido y ondas.', 'Processing draws an 80 × 80 grid with ten noise and wave patterns.')),
        ])),
        block(p, ('Comportamiento', 'Behavior'), ('Calma, excitación y color.', 'Calm, excitement and color.'), items(p, [
            (('Una zona de calma', 'A calm zone'),
             ('Con poca luz el patrón queda casi quieto. Pasado el 50 %, la velocidad crece con una curva cúbica: la lámpara “se despierta” de golpe.',
              'In low light the pattern barely moves. Past 50 %, speed grows on a cubic curve: the lamp “wakes up” suddenly.')),
            (('Cambios por excitación', 'Changes driven by excitement'),
             ('La probabilidad de saltar a otro de los diez patrones aumenta con la luz, y cada cambio se mezcla de forma gradual para no cortar.',
              'The chance of jumping to another of the ten patterns rises with light, and each change blends gradually instead of cutting.')),
            (('La temperatura es color', 'Temperature is color'),
             ('El tono va de naranjas a azules y violetas a medida que sube la temperatura; con mucha luz, el color se lava.',
              'Hue moves from oranges to blues and violets as temperature rises; under strong light, color washes out.')),
        ])),
        block(p, ('Ficha técnica', 'Specs'), ('Hardware y software.', 'Hardware and software.'), spec(p, [
            (('Placa', 'Board'), ('ESP32', 'ESP32')),
            (('Sensores', 'Sensors'), ('Fotorresistencia y temperatura analógica', 'Photoresistor and analog temperature')),
            (('Firmware', 'Firmware'), ('Arduino (C++)', 'Arduino (C++)')),
            (('Visual', 'Visuals'), ('Processing', 'Processing')),
            (('Conexión', 'Link'), ('Serie, 115.200 baudios', 'Serial, 115,200 baud')),
            (('Web', 'Web'), ('Port a JavaScript y canvas', 'JavaScript and canvas port')),
        ])),
        block(p, ('Qué sigue', 'What\'s next'), ('Datos en vivo sobre papel electrónico.', 'Live data on electronic paper.'), paras(p, [
            ('Estoy probando la conexión del ESP32 con una pantalla e-ink para mostrar datos en vivo, como la cantidad de personas jugando Pegote en ese momento.',
             'I am testing the ESP32 with an e-ink display to show live data, such as how many people are playing Pegote at that moment.'),
        ])),
    ])
    d = dict(name='Lámpara viva', description='Case study: Living lamp, an ESP32 lamp whose generative pattern reacts to ambient light and temperature.',
             label=('Proyecto propio · 2026', 'Side project · 2026'),
             lede=('Una lámpara que reacciona a su entorno: la luz y la temperatura del ambiente controlan un patrón generativo.',
                   'A lamp that reacts to its surroundings: ambient light and temperature drive a generative pattern.'),
             meta=[(ROLE, ('Hardware y código creativo', 'Hardware and creative code')), (YEAR, '2026'),
                   (STATUS, ('Prototipo', 'Prototype')), (STACK, 'ESP32 · Processing')],
             cover=cover, next=('social-monitor', ('Social Monitor', 'Social Monitor')), lamp=True)
    d['name_en'] = 'Living lamp'
    return p, d, body


def monitor():
    p = Page('monitor')

    def cover(p):
        return f'''<div class="cs-cover cs-cover-field" data-unveil style="background:var(--f-monitor);min-height:clamp(280px,40vw,520px)">
          <div class="sources" aria-hidden="true" style="max-width:720px;justify-content:center;margin:0">
            <span class="source">Google News</span><span class="source">GDELT</span><span class="source">Mastodon</span><span class="source">Hacker News</span><span class="source off">Reddit</span><span class="source off">YouTube</span><span class="source off">Bluesky</span>
          </div>
        </div>'''

    body = ''.join([
        block(p, ('Contexto', 'Context'), ('Escuchar a una marca sin una plataforma pesada.', 'Listening for a brand without a heavy platform.'), paras(p, [
            ('Las plataformas de social listening suelen ser costosas y complejas de configurar. Quería una alternativa liviana: decirle qué marca seguir y recibir, cada semana, lo que realmente importa.',
             'Social listening platforms tend to be expensive and complex to set up. I wanted a lightweight alternative: tell it which brand to follow and receive, every week, what actually matters.'),
        ])),
        block(p, ('Cómo funciona', 'How it works'), ('De la mención al reporte.', 'From mention to report.'), pipeline(p, [
            (('Recolectar', 'Collect'), ('Conectores a noticias, redes y foros buscan los términos de cada marca.', 'Connectors to news, social networks and forums search for each brand\'s terms.')),
            (('Clasificar', 'Classify'), ('Claude evalúa cada mención: relevancia, sentimiento, temas, quejas y urgencia.', 'Claude scores each mention: relevance, sentiment, topics, complaints and urgency.')),
            (('Guardar', 'Store'), ('Menciones, marcas y cuentas viven en Supabase.', 'Mentions, brands and accounts live in Supabase.')),
            (('Programar', 'Schedule'), ('Un cron de Vercel recolecta todos los días.', 'A Vercel cron collects every day.')),
            (('Reportar', 'Report'), ('Los lunes genera el reporte semanal de cada marca.', 'On Mondays it generates each brand\'s weekly report.')),
        ])),
        block(p, ('Decisiones', 'Decisions'), ('Simple de empezar, fácil de extender.', 'Simple to start, easy to extend.'), items(p, [
            (('Valor desde el primer día', 'Value from day one'),
             ('Google News, GDELT, Mastodon y Hacker News funcionan sin credenciales. Reddit, YouTube y Bluesky se activan solos al cargar sus claves.',
              'Google News, GDELT, Mastodon and Hacker News work without credentials. Reddit, YouTube and Bluesky switch on as soon as their keys are added.')),
            (('Un conector, una interfaz', 'One connector, one interface'),
             ('Cada fuente implementa la misma interfaz: sumar una nueva es escribir un archivo y registrarlo.',
              'Every source implements the same interface: adding a new one means writing one file and registering it.')),
            (('Respetar los límites', 'Respecting limits'),
             ('El sistema respeta los topes de cada servicio, como un pedido cada 5 segundos en GDELT o la cuota diaria de YouTube.',
              'The system honors each service\'s caps, such as one request every 5 seconds on GDELT or YouTube\'s daily quota.')),
            (('Probar sin infraestructura', 'Testing without infrastructure'),
             ('Scripts para correr solo la recolección, o la recolección con IA, sin base de datos.',
              'Scripts to run only collection, or collection plus AI, without a database.')),
        ])),
        block(p, ('Stack', 'Stack'), ('Herramientas.', 'Tools.'), spec(p, [
            (('Aplicación', 'App'), ('Next.js', 'Next.js')),
            (('Datos y cuentas', 'Data and auth'), ('Supabase', 'Supabase')),
            (('Clasificación', 'Classification'), ('Claude API', 'Claude API')),
            (('Tareas programadas', 'Scheduled jobs'), ('Vercel Cron', 'Vercel Cron')),
            (('Fuentes', 'Sources'), ('7 conectores', '7 connectors')),
            (('Salida', 'Output'), ('Reporte semanal por marca', 'Weekly report per brand')),
        ])),
    ])
    d = dict(name='Social Monitor', description='Case study: Social Monitor, an AI-assisted brand monitoring tool built with Next.js, Supabase and Claude.',
             label=('Proyecto propio · 2026', 'Side project · 2026'),
             lede=('Monitoreo de marca con IA: reúne lo que se publica sobre una marca en la web y lo convierte en un reporte semanal.',
                   'AI-assisted brand monitoring: it gathers what is published about a brand across the web and turns it into a weekly report.'),
             meta=[(ROLE, ('Diseño y desarrollo', 'Design and development')), (YEAR, '2026'),
                   (STATUS, ('Prototipo funcional', 'Working prototype')), (STACK, 'Next.js · Claude')],
             cover=cover, next=('weeklygoals', ('WeeklyGoals', 'WeeklyGoals')))
    return p, d, body


def goals():
    p = Page('goals')

    def cover(p):
        return f'''<figure class="cs-cover cs-cover-field" data-unveil style="background:var(--f-goals)">
          <img src="/assets/img/projects/weeklygoals-app.webp" alt="" style="width:min(340px,80%);height:auto;border-radius:12px;box-shadow:0 30px 60px -20px rgba(0,0,0,.7),0 0 0 1px rgba(255,255,255,.08)"/>
        </figure>
        {p.tr(('Interfaz real de la app, con objetivos de ejemplo.', "The app's real interface, with sample goals."), tag='p', attrs=' class="cs-caption"')}'''

    body = ''.join([
        block(p, ('Contexto', 'Context'), ('La semana, a un clic.', 'The week, one click away.'), paras(p, [
            ('Quería ver solo los objetivos de esta semana, sin abrir una app de tareas completa ni perderme en listas largas. Vive en la barra de menú de la Mac: un clic y está.',
             'I wanted to see only this week\'s goals, without opening a full task manager or getting lost in long lists. It lives in the Mac menu bar: one click and it is there.'),
        ])),
        block(p, ('Qué hace', 'What it does'), ('Pocas funciones, bien resueltas.', 'Few features, done well.'), items(p, [
            (('Progreso de la semana', 'Weekly progress'),
             ('Un anillo muestra el porcentaje cumplido y el conteo de completados de lunes a domingo.',
              'A ring shows the completion percentage and the count of finished goals from Monday to Sunday.')),
            (('Días como fichas', 'Days as chips'),
             ('Cada día muestra su avance (por ejemplo, 2/3) y se marca en verde cuando está completo.',
              'Each day shows its progress (for example, 2/3) and turns green when complete.')),
            (('Navegar semanas', 'Navigate weeks'),
             ('Ir a la semana anterior o siguiente, y volver a hoy con un botón.',
              'Go to the previous or next week, and jump back to today with one button.')),
            (('Recordatorios', 'Reminders'),
             ('Notificaciones de lunes a viernes al mediodía y a las 17:00 para revisar y cerrar el día.',
              'Notifications Monday to Friday at noon and at 5 pm to review and close the day.')),
            (('Rápido de mantener', 'Quick to maintain'),
             ('Agregar, completar, borrar y limpiar los completados de un día. Todo se guarda en la computadora.',
              'Add, complete, delete and clear a day\'s completed goals. Everything is stored on the computer.')),
        ])),
        block(p, ('Stack', 'Stack'), ('Nativo de macOS.', 'Native to macOS.'), spec(p, [
            (('Interfaz', 'UI'), ('SwiftUI', 'SwiftUI')),
            (('Formato', 'Format'), ('App de barra de menú (MenuBarExtra)', 'Menu bar app (MenuBarExtra)')),
            (('Avisos', 'Alerts'), ('UserNotifications', 'UserNotifications')),
            (('Datos', 'Data'), ('Guardado local', 'Local storage')),
            (('Distribución', 'Distribution'), ('Instalador .dmg', '.dmg installer')),
            (('Uso', 'Use'), ('Diario, personal', 'Daily, personal')),
        ])),
    ])
    d = dict(name='WeeklyGoals', description='Case study: WeeklyGoals, a native macOS menu bar app for planning weekly goals day by day.',
             label=('Proyecto propio · 2026', 'Side project · 2026'),
             lede=('Una app nativa para la barra de menú de macOS para planificar objetivos semanales día por día.',
                   'A native macOS menu bar app for planning weekly goals day by day.'),
             meta=[(ROLE, ('Diseño y desarrollo', 'Design and development')), (YEAR, '2026'),
                   (STATUS, ('En uso diario', 'In daily use')), (STACK, 'SwiftUI')],
             cover=cover, next=('pegote', ('Pegote', 'Pegote')))
    return p, d, body


SLUGS = {'pegote': pegote, 'living-lamp': lamp, 'social-monitor': monitor, 'weeklygoals': goals}

if __name__ == '__main__':
    for slug, fn in SLUGS.items():
        p, d, body = fn()
        out = os.path.join(ROOT, 'projects', slug, 'index.html')
        os.makedirs(os.path.dirname(out), exist_ok=True)
        with open(out, 'w') as f:
            f.write(page_html(p, d, body))
        print('wrote', os.path.relpath(out, ROOT))
